In [19]:
# Write a program to implement the naïve Bayesian classifier andthekNN classifier for a sample training data set stored as a .CSVfile. Also compute performance matrices for the said algorithmand predict the outcome for user input (dataset: winequalityN.csv)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [20]:
df = pd.read_csv('winequalityN.csv')
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [21]:
# For checking null value: df.isna().sum()
# For checking value type: df.info()

df.isna().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [22]:
# here we are having too less null value but in so many fields so we will remove that fields in place of replace
df = df.dropna()

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6463 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   type                  6463 non-null   object
 1   fixed acidity         6463 non-null   float64
 2   volatile acidity      6463 non-null   float64
 3   citric acid           6463 non-null   float64
 4   residual sugar        6463 non-null   float64
 5   chlorides             6463 non-null   float64
 6   free sulfur dioxide   6463 non-null   float64
 7   total sulfur dioxide  6463 non-null   float64
 8   density               6463 non-null   float64
 9   pH                    6463 non-null   float64
 10  sulphates             6463 non-null   float64
 11  alcohol               6463 non-null   float64
 12  quality               6463 non-null   int64
dtypes: float64(11), int64(1), object(1)
memory usage: 706.9+ KB

In [24]:
# Here "type" will be used as feature/target but its data type is object. So will convert that into numeric data.
le = LabelEncoder()
df['type'] = le.fit_transform(df['type'])
df.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,1,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,1,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,1,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [25]:
# Now we will divide those into target and feature
X = df.drop(columns= 'quality')
y = df['quality']

In [26]:
# Now train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
# As we are also using KNN we will Scale X train and test
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform(X_test)

In [28]:
# Now we will create both model one by one
model_nb = GaussianNB()
model_knn = KNeighborsClassifier(n_neighbors=3)

In [29]:
model_nb.fit(X_train, y_train)
model_knn.fit(X_train_scaler, y_train)

KNeighborsClassifier(n_neighbors=3)

In [30]:
y_pred_nb = model_nb.predict(X_test)
y_pred_knn = model_knn.predict(X_test_scaler)

In [31]:
# Here in precision and recall average = "weighted" is used
# because our output is not only boolean like (0/1) Its belongs 5,6,7,8,.. as we can see in quality column's value

accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb, average='weighted')
recall_nb = recall_score(y_test, y_pred_nb, average='weighted')

accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn, average='weighted')
recall_knn = recall_score(y_test, y_pred_knn, average='weighted')

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [32]:
print("Naive Bayes Classifier:")
print("Accuracy:", accuracy_nb * 100)
print("Precision:", precision_nb * 100)
print("Recall:", recall_nb * 100)

print("\nK-Nearest Neighbors Classifier:")
print("Accuracy:", accuracy_knn * 100)
print("Precision:", precision_knn * 100)
print("Recall:", recall_knn * 100)

Naive Bayes Classifier:
Accuracy: 40.21655065738592
Precision: 43.34585716345944
Recall: 40.21655065738592

K-Nearest Neighbors Classifier:
Accuracy: 55.375096674400616
Precision: 54.60850258737864
Recall: 55.375096674400616

In [33]:
# Now as we have been told to predict outcome of user input.
u_type = input("Enter type (red / white) : ")
u_fixed_acidity = input("Enter fixed acidity : ")
u_volatile_acidity = input("Enter volatile acidity : ")
u_citric_acid = input("Enter citric acid : ")
u_residual_sugar = input("Enter residual sugar : ")
u_chlorides = input("Enter chlorides : ")
u_free_sulfur_dioxide = input("Enter free sulfur dioxide : ")
u_total_sulfur_dioxide = input("Enter total sulfur dioxide : ")
u_density = input("Enter density : ")
u_pH = input("Enter pH : ")
u_sulphates = input("Enter sulphates : ")
u_alcohol = input("Enter alcohol : ")

# As user will input red/white in type we will convert that into numeric value using same Encoder where we converted type of dataset of training

wine_type = le.transform([u_type])[0]

X_user = pd.DataFrame({
    'type': [wine_type],
    'fixed acidity': [u_fixed_acidity],
    'volatile acidity': [u_volatile_acidity],
    'citric acid': [u_citric_acid],
    'residual sugar': [u_residual_sugar],
    'chlorides': [u_chlorides],
    'free sulfur dioxide': [u_free_sulfur_dioxide],
    'total sulfur dioxide': [u_total_sulfur_dioxide],
    'density': [u_density],
    'pH': [u_pH],
    'sulphates': [u_sulphates],
    'alcohol': [u_alcohol]
})

X_user_scaled = scaler.transform(X_user)

prediction_nb = model_nb.predict(X_user)
prediction_knn = model_knn.predict(X_user_scaled)

print("\nNaive Bayes Classifier Prediction:")
print("Predicted Quality:", prediction_nb[0])

print("\nK-Nearest Neighbors Classifier Prediction:")
print("Predicted Quality:", prediction_knn[0])

Enter type (red / white) : white
Enter fixed acidity : 8.6
Enter volatile acidity : 0.23
Enter citric acid : 0.4
Enter residual sugar : 4.2
Enter chlorides : 0.035
Enter free sulfur dioxide : 17
Enter total sulfur dioxide : 109
Enter density : 0.9947
Enter pH : 3.14
Enter sulphates : 0.53
Enter alcohol : 9.7

Naive Bayes Classifier Prediction:
Predicted Quality: 6

K-Nearest Neighbors Classifier Prediction:
Predicted Quality: 6